version: "3"

services: 
    web:
        container_name: acmeapp
        restart: always
        build: .
        ports: 
            - "5000:3000"
        links: 
            - mongo
        volumes: 
            - .:/usr/src/app
    mongo:
        container_name: mongoacmedatabase
        image: mongo
        ports: 
            - "27019:27017"
        logging: 
            driver: none